### ISSUE TITLE
Write-Verbose should be used rather than Write-Host

### ISSUE THREAD

**Issue by randomnote1** [WetHat/MarkdownToHtml#1]
Write-Verbose should be used rather than Write-Host throughout this module. Write-Host tends [break stuff unintentionally](https://www.jsnover.com/blog/2013/12/07/write-host-considered-harmful/) as well as clutter up the console. The preferred method is to use Write-Verbose so the end user can see what is happening when they want to.

**Comment by WetHat** [comment]
Hi randomnote1,

I actually agree with the article you link to in the description. I'm going to update the code asap.

WetHat

**Comment by WetHat** [comment]
Fixed in v1.2.8
