### ISSUE TITLE
PHP Syntax Highlighting

### ISSUE THREAD

**Issue by thecliguy** [WetHat/MarkdownToHtml#15]
Is there a procedure to follow to add syntax highlighting for PHP?

**Comment by WetHat** [comment]
Sure.

You would:
1. navigate to [Getting highlight.js](https://highlightjs.org/download/)
2. scroll down to _Custom Package_ section and select one or more language you want. E.g. _PHP_ and _PHP Template_
3. click on download. This will download a ZIP file with the required resources including **all** highlighting styles.
4. if you want to use the new styles on a conversion project created by [New-StaticHTMLSiteProject](https://github.com/WetHat/MarkdownToHtml/blob/master/Documentation/New-StaticHTMLSiteProject.md), copy `highlight.pack.js` from the ZIP file over to the `Template/js` directory of your project. If you are not using conversion projects, create a new custom template with [New-HTMLTemplate](https://github.com/WetHat/MarkdownToHtml/blob/master/Documentation/New-HTMLTemplate.md) and copy  `highlight.pack.js` from the ZIP file over to the `js` directory of the custom template.
5. mission accomplished. Enjoy the new highlighting styles.

Now, if you want to use any the highlighting styles that came with the download package, do this:
1. Copy  one or more styles form the ZIP file to the `styles` directory of the template you are going to use.
2. Edit `md-template.html` in the template directory and load the style in the head section like so:
~~~ html
<link rel="stylesheet" type="text/css" href="styles/my-favorite-style.css" />
~~~

**Comment by thecliguy** [comment]
Thank you, much appreciated.

**Comment by WetHat** [comment]
I noticed the confusing use of 'style' in my reply. I hope you had no big issues with this. I've cleaned the mess up and made a FAQ out of it. In case you ever need to look it up again you will find it at:
[Adding Syntax Highlighting for a New Language](https://github.com/WetHat/MarkdownToHtml/wiki/Adding-Syntax-Highlighting-for-a-New-Language)
