### ISSUE TITLE
MarkdownToHtml verbosity

### ISSUE THREAD

**Issue by TheCarnacki** [WetHat/MarkdownToHtml#48]
Using Powershell 5.1 and 7.3 I'm unable to turn off MarkdownToHtml's (version 2.7.1) verbosity. Here's the code I'm using:

`Convert-MarkdownToHTML -Verbose:$false -Path (Join-Path -Path $content_dir -ChildPath '*.md') -SiteDirectory $content_dir -Template '.\markdown' | Out-Null`

and the output is typically:

```
jeffr@CALLISTO: D:\Documents\hua $ del .\blog\* ; .\hua.ps1 .\hua.cfg
VERBOSE: Using parser extensions common
VERBOSE: Publishing to 'D:\Documents\hua\content' using HTML template '.\markdown'.
VERBOSE: Scanning .\content\*.md for Markdown files except
VERBOSE: markdown-2.md -> markdown-2.html
VERBOSE: markdown.md -> markdown.html
```

I would expect there to be no output if it runs successfully or to be able to switch this off.

**Comment by WetHat** [comment]
Fixed in release v2.8.0
